### ISSUE TITLE
Migrate from pep517 to using build in tests and workflows

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#1065]
# Description

Given https://github.com/pypa/pep517/pull/83 it seems that `pep517` is deprecated and we should switch to using [`build`](https://pypi.org/project/build/). There is [documentation for `build`](https://python-build.readthedocs.io/en/latest/) and a new Issue that tracks things https://github.com/pypa/pep517/issues/91, but in short we should be using

```
python -m pip install build
python -m build --sdist --wheel --outdir dist/ .
```

From the `build` docs section on "[Difference from other tools](https://python-build.readthedocs.io/en/latest/#difference-from-other-tools)":

> ```
>python -m pep517.build
>```
>`python-build` implements a CLI tailored to end users.
>
>`pep517.build` contained a proof-of-concept of a [PEP 517](https://www.python.org/dev/peps/pep-0517) frontend. It "_implement[ed] essentially the simplest possible frontend tool, to exercise and illustrate how the core functionality can be used_". It has since been [deprecated and is scheduled for removal](https://github.com/pypa/pep517/pull/83).

Thanks to @pganssle for [the alerting Tweet](https://twitter.com/pganssle/status/1303419420518346759?s=20).

cc @alexander-held @henryiii @gordonwatts

**Comment by matthewfeickert** [comment]
It seems that there is now equivalent yet in `build` for [`pep517.check`](https://pypi.org/project/pep517/0.8.2/)

> To test the build backend for a project, run in a system shell:
>```
>python3 -m pep517.check path/to/source  # source dir containing pyproject.toml
>```

which is used by `pyhf` for publishing:

https://github.com/scikit-hep/pyhf/blob/cab1d8d4392bb76ddd16553f90ab81a6dfd0494a/.github/workflows/publish-package.yml#L32-L34

I'll need to read more through the discussion and issues that exist to see if it exists, but I'll also be a bit annoying and tag @webknjaz now (:wave: hello again! Feel free to ignore this) as he seems to be highly in the know.

**Comment by pganssle** [comment]
To be clear, this sudden `pep517.build` deprecation is very unfortunate to my mind, not least of which because `python-build` is in pretty early alpha and has a few major show-stopping bugs like [this one](https://github.com/FFY00/python-build/issues/97). `pep517.build` is not perfect either, mind you, but I think right now for my projects I'm at something close to a toss-up between "pin `pep517`" and "switch to `build`". Especially since [the console script name might have to change](https://github.com/FFY00/python-build/issues/101) (and it would be hard to implement a long deprecation period for that).

With regards to this:

> It seems that there is now equivalent yet in `build` for [`pep517.check`](https://pypi.org/project/pep517/0.8.2/)

It's not 100% clear to me that this is necessary. As far as I can tell `pep517.check` just does the checks that the project does before doing a build anyway, so if you're doing a build _anyway_, you aren't losing anything (it's just that the failure will show up in the build step, rather than in the "check the build" step).

**Comment by matthewfeickert** [comment]
> As far as I can tell `pep517.check` just does the checks that the project does before doing a build anyway, so if you're doing a build _anyway_, you aren't losing anything

Yeah, I think you're right. I was just looking at the logs for this PR and the following screeenshot is showing the relevant section from 

https://github.com/scikit-hep/pyhf/blob/cab1d8d4392bb76ddd16553f90ab81a6dfd0494a/.github/workflows/publish-package.yml#L32-L37

![compare_of_pep517check_and_build](https://user-images.githubusercontent.com/5142394/93146210-d2891700-f6b3-11ea-9fff-75d0f019e6f4.png)

It seems that the same checks run in `pep517.check` are run in `pep517.build` and `build` and so there might not be an actual need for a `check` API.
