### ISSUE TITLE
use strategy 0 for user-provided gradients in minuit

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#1172]
# Description

since we have exact gradient we can disable the checks minuit does

cc @alexander-held

**Comment by alexander-held** [comment]
Some reference here: https://iminuit.readthedocs.io/en/stable/reference.html#iminuit.Minuit.strategy, in particular:

> 0: Fast. Does not check a user-provided gradient. Does not improve Hesse matrix at minimum. Extra call to hesse() after migrad() is always needed for good error estimates. If you pass a user-provided gradient to MINUIT, convergence is faster.

> 1: Default. Checks user-provided gradient against numerical gradient. Checks and usually improves Hesse matrix at minimum. Extra call to hesse() after migrad() is usually superfluous. If you pass a user-provided gradient to MINUIT, convergence is slower.

Strategy 0 seems mandatory when using gradients, and may be fine for some/most fits when not using them too. The `.hesse` call is a good addition when using strategy 0. Strategy 1 seems like a good default when not using exact gradients. Unfortunately there's no easy way to switch with the current optimizer structure in `pyhf`, since the strategy cannot be set through the constructor (https://github.com/scikit-hep/iminuit/issues/466).
