### ISSUE TITLE
Schema missing from docs

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#686]
# Description

Need to use something like [sphinx-jsonschema](https://pypi.org/project/sphinx-jsonschema/) to fix it up.

# Expected Behavior

I was able to navigate to the schemas...

# Actual Behavior

Schemas are gone :o

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kratsg** [comment]
Additionally, we might want to check if symbolic links can be supported -- or if we can somehow write `conf.py` to always copy over the schema files into the right location every time.

**Comment by Sinclert** [comment]
Hi @kratsg ,

I am tracking this issue because it was mentioned in the [HEP-Data "individual pyhf JSON support"](https://github.com/HEPData/hepdata/issues/164#issuecomment-582998142) issue.

It seems that there was a [commit](https://github.com/scikit-hep/pyhf/commit/732827583fb2c2ad747e690805e30e4c8e343e94#diff-e9f950f17198d3d5e3122a44230a09b9L106) where the documentation creation was changed from using the `Makefile`, to not using it. Given that the `Makefile` rule for generating HTML documentation contains the following line of code:
```shell
rsync -r ../src/pyhf/schemas/ $(BUILDDIR)/html/schemas
```

I think that may be the reason why links to any "https://scikit-hep.org/pyhf/schemas/1.0.0/..." are broken.

Do you remember why this line was changed?
Could we change it back?

**Comment by kratsg** [comment]
hi @Sinclert , so this is because the recommended way to build the sphinx docs is not via the Makefile, but via https://github.com/scikit-hep/pyhf/blob/2ba5ec88d3ab27c15e65aaec6bf40a1ae6231b83/.github/workflows/ci.yml#L106-L110

```yaml
    - name: Test and build docs
      run: |
        python -m doctest README.md
        python setup.py build_sphinx
        touch docs/_build/html/.nojekyll
```

as such - it's been just slightly annoying to migrate this into sphinx correctly.

**Comment by Sinclert** [comment]
Is there any particular reason why is not recommended?

I see that in the official Sphinx webpage they address the invocation from a `Makefile`, as _"make life even easier for you"_ ([reference](https://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build)).

**Comment by kratsg** [comment]
> I see that in the official Sphinx webpage they address the invocation from a `Makefile`, as _"make life even easier for you"_ ([reference](https://www.sphinx-doc.org/en/master/usage/quickstart.html#running-the-build)).

Docs on this is here: https://www.sphinx-doc.org/en/master/usage/advanced/setuptools.html

We rely on the (semantic) versioning set up, especially for dev-versioning, and it is quite impossible to get this set through a makefile. We need this so we can use `pkg_resources. get_distribution` to grab the correct versions.

**Comment by Sinclert** [comment]
It highly depends on how the _"https://scikit-hep.org/pyhf/schemas"_ URL is going to be used, right?

I can think of 2 aspects to consider:

---

1. **Backwards compatibility of links:**
There are some links pointing to URLs like _"https://scikit-hep.org/pyhf/schemas/1.0.0/model.json"_ that are not working right now. That is because of the issue I pointed in [this comment](https://github.com/scikit-hep/pyhf/issues/686#issuecomment-589187261). I don't know the importance of keeping those old links working, you better know, but that is something [sphinx-jsonschema](https://pypi.org/project/sphinx-jsonschema/) is not going to help with. So, there are 2 options:

    - **Option A)** Do nothing.
    - **Option B)** Add the following line to [this CI step](https://github.com/scikit-hep/pyhf/blob/master/.github/workflows/ci.yml#L110):


    ```shell
    rsync -r docs/schemas  docs/_build/html/schemas
    ```

---

2. **Schema JSONs format:**
The schema JSON files can be shown in the documentation by adding a _"schemas"_ section to the main index, with different version headers (_1.0.0_, _1.1.0_...) within. The schemas are currently following the _"JSON Pointer"_ notation. Again, I don't know how important it is to show the _"resolved JSON"_ schemas, or if the _"pointer JSON"_ schemas are good enough. So, I can think of 2 options:

    - **Option A)** Pointer JSON format:
        - **Advantage:** no need for [sphinx-jsonschema](https://pypi.org/project/sphinx-jsonschema/).
        - **Disadvantage:** no self-contained schemas. (that is how it was before [the commit](https://github.com/scikit-hep/pyhf/commit/732827583fb2c2ad747e690805e30e4c8e343e94#diff-e9f950f17198d3d5e3122a44230a09b9L106)).

    - **Case B)** Resolved JSON format:
        - **Advantage:** The schemas are self-contained.
        - **Disadvantage:** need [sphinx-jsonschema](https://pypi.org/project/sphinx-jsonschema/) extension.

---

It is not clear to me if this issue was opened because of reason 1 (_"Broken links"_), or reason 2 (_"JSONs not appearing in the format you want"_). [Sphinx-jsonschema](https://pypi.org/project/sphinx-jsonschema/) can only help on the second one.

Could you clarify?

**Comment by kratsg** [comment]
To clarify, one reason why I was suggesting `sphinx-jsonschema` was to enforce that the files existed in the docs. We have our sphinx-build configured to consider all warnings as errors (and a missing file is considered a warning). So `sphinx-jsonschema` was my initial idea as a canary to identify when a schema we expected to be in the docs is not included as part of the built docs.

I did not intend for `sphinx-jsonschema` to replace the URLs that you see in `$id` for each schema that is referred to -- but rather as a way to incorporate parts of the schema into our documentation to reference as part of.. documentation.

I do not necessarily know what you mean by self-contained schemas (do you mean all schemas in a single JSON?). Likely, option A is what I would prefer if I'm understanding you correctly.

**Comment by Sinclert** [comment]
I see.

Yes, by _"self-contained"_ I was referring to the fact that if a JSON schema _"A"_ refers to JSON schema _"B"_, B's schema is written inside A's schema. Ok, so it seems that is **NOT** what is desired. Noted.

Now, even if `sphinx-jsonschema` or other technique is used to ensure JSON's presence, **that is still not solving the backwards compatibility of links I mentioned in my previous comment**.

Currently, none of these are working:
- https://scikit-hep.org/pyhf/schemas/1.0.0/defs.json
- https://scikit-hep.org/pyhf/schemas/1.0.0/measurement.json
- https://scikit-hep.org/pyhf/schemas/1.0.0/model.json
- https://scikit-hep.org/pyhf/schemas/1.0.0/workspace.json

Which seems to be the issue pointed in [this HEP-Data issue](https://github.com/HEPData/hepdata/issues/164#issuecomment-582998142).

- Do you want to track this on a different issue?

- If not, could I create a PR just adding this line to [this specific CI step](https://github.com/scikit-hep/pyhf/blob/master/.github/workflows/ci.yml#L110)?
```
rsync -r src/pyhf/schemas docs/_build/html/schemas
```

**Comment by kratsg** [comment]
@Sinclert , see #791 for the fix. Those urls will be working again after that PR is in. Additionally, I've added a check to enforce that we don't lose them in the future. I didn't want to add it in the CI step (because I want it to also work locally) so I like the solution I've put in.

**Comment by kratsg** [comment]
We do a mix of self-contained -- versus not. `defs.json` is meant to be what you'd consider a self-contained schema -- although because of the way the JSON schemas are written, it's not easy to define something there that would be pulled out easily by our validation (which doesn't handle pointers).

That is, `workspace.json` was made, so we could pass into https://github.com/scikit-hep/pyhf/blob/73da08d9a9a37d58b672ef6bfa5ef7f515e02e4d/src/pyhf/utils.py#L39-L54 . It's not clear to me if it's possible to have a single schema for a given version or not in a single file and use our validation to validate against pointers within the schema (e.g. `1.0.0.json#definitions/workspace` versus `workspace.json`). I can try tomorrow to see if this is possible -- and if it is, since HEPData will be the first to refer to these schemas, I can refactor our 1.0.0 to at least be self-contained to get ready for this (without affecting existing released likelihoods).
