### ISSUE TITLE
altair example doesn't render  in docs

### ISSUE THREAD

**Issue by lukasheinrich** [scikit-hep/pyhf#720]
# Description

I would expect this to show the altair plot

https://scikit-hep.org/pyhf/examples/notebooks/altair.html

like here

https://altair-viz.github.io/gallery/selection_layer_bar_month.html

**Comment by kratsg** [comment]
That's because they're using a custom sphinx extension (undocumented as far as I can tell): https://github.com/altair-viz/altair/blob/3934e0bd8ca770833304944642a212aeec256ca1/doc/conf.py#L39-L44 and https://github.com/altair-viz/altair/blob/6b40e6ef452148f787cae769860ab17b3584c5a6/altair/sphinxext/altairplot.py#L2-L52

**Comment by matthewfeickert** [comment]
@lukasheinrich this seems to have been resolved at some point as https://scikit-hep.org/pyhf/examples/notebooks/altair.html now has a working interactive Altair visualization in the docs. I'll go ahead and close this.
