### ISSUE TITLE
Bug Report: Docs broken by nbformat update and scrapbook error

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/pyhf#722]
# Description

The nightly tests show that the [docs are currently breaking in their build](https://github.com/scikit-hep/pyhf/runs/376577841#step:6:85):

```
reading sources... [ 88%] examples/notebooks/multiBinPois
/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/m2r.py:652: RemovedInSphinx30Warning: app.add_source_parser() does not support suffix argument. Use app.add_source_suffix() instead.
  app.add_source_parser('.md', M2RParser)
ERROR:traitlets:Notebook JSON is invalid: {'number_2d_successpoints': 225} is not valid under any of the given schemas
```

From comparing the output of `python -m pip list` from the successful nightly build the day before, it seems that this is an error that is getting raised by [`nbfromat v5.0`](https://nbformat.readthedocs.io/en/5.0.3/changelog.html#id1)

```
$ diff pip_list_succeed.txt pip_list_fail.txt
60c60
< nbformat 4.4.0
---
> nbformat 5.0.3
65c65
< numpy 1.18.0
---
> numpy 1.18.1
68c68
< packaging 19.2
---
> packaging 20.0
105c105
< PyYAML 5.2
---
> PyYAML 5.3
```

This appears to be some conflict between `nbformat` and how [`scrapbook`](https://github.com/nteract/scrapbook) is saving information, as if the final cell of the notebook

```python
sb.glue("number_2d_successpoints", len(X))
```

is commented out then the error does not occur.

# Expected Behavior

The docs build without error.

# Actual Behavior

The docs break in the build

# Steps to Reproduce

```
# from inside the pyhf repo
$ python -m pip install -e .[complete]
$ cd docs
$ make html
```

If one also tries to run the `multiBinPois` Jupyter notebook the error is also produced at the end when it tires to autosave

![nbformat_fail](https://user-images.githubusercontent.com/5142394/71931241-f67a7d00-3162-11ea-92ae-79509ae51d4f.png)

```
Notebook validation failed: {'name': 'number_2d_successpoints', 'data': 225, 'encoder': 'json', 'version': 1} is not valid under any of the given schemas:
{
 "name": "number_2d_successpoints",
 "data": 225,
 "encoder": "json",
 "version": 1
}
```

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment]
@lukasheinrich @kratsg This is kind of a showstopper until we can fix this, so if either of you have ideas that would be great.

Not to bug either of them, but tagging @MSeal and @willingc :wave: (please untag yourselves if this is annoying, sorry in advance) as they are `scrapbook` devs and so may be able to point out the issue quickly.

**Comment by MSeal** [comment]
@matthewfeickert The issue is (mostly) unrelated to scrapbook. It's that scrapbook requires a notebook of format >= 4.2. Previous to the nbformat 5 release nbformat in the notebook server was ignoring older formatted notebooks and pretending they were the latest version (4.3 at the time). Likely the notebook you are saving the scrapbook item to is 4.0 or 4.1 version and was created when that was the standard in jupyter classic. If you edit the file you can check the nbformat and nbformat_minor versions to see if this is the case. I was able to reproduce by taking a working notebook and changing the minor version to 4.1 which had different rules for what data could be in outputs. If you load the notebook in jupyter lab once instead of classic it will automatically upgrade the document to version 4.4 when you save.

**Comment by matthewfeickert** [comment]
Thank you so much, @MSeal! This very nicely fixes things for us.

**Comment by MSeal** [comment]
Np, sorry the nbformat release caused noise

**Comment by matthewfeickert** [comment]
More learning than noise. :)
