### ISSUE TITLE
Workspace.version is not set when loading in a workspace with a version

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#801]
# Description

See the title.

# Expected Behavior

`Workspace.version is not None`

# Actual Behavior

`Workspace.version is None`

# Steps to Reproduce

```python
import pyhf, json

ws = pyhf.Workspace(json.load(open('workspace.json')))
assert ws.version is not None
assert ws.version == ws['version']
```

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by kanishk16** [comment]
I am now moving on to this issue but I'm unable to reproduce the error due to the following exception raised in the workspace.py file
```
KeyError: 'channels' 
```
which is due to as per the workspace.json file 
```
Unable to load schema from 'http://json-schema.org/draft-06/schema'. No schema request service available(768)
```

I am afraid that I couldn't find a solution to the above problem.

**Comment by kratsg** [comment]
@kanishk16 , not sure how you're getting that error...

```
>>> import pyhf, json
>>> ws = pyhf.Workspace(json.load(open('my-workspace.json')))
>>> ws.version
>>> ws['version']
'1.0.0'
```

works for me just fine. Are you trying to load in the `pyhf/schemas/1.0.0/workspace.json` file as a workspace? It's a schema describing a workspace, not a workspace itself.

**Comment by kanishk16** [comment]
Sorry for the late reply @kratsg ...Yes, I was trying to load `pyhf/schemas/1.0.0/workspace.json`. Since I am using Google Colab, I am not sure if there already exists a workspace.json.
I might not be well versed about it. From what I know, not sure if you are talking about this, there exists a workspace.json corresponding to the workspace of each user. But, what if the workspace.json doesn't exist only (never really thought of)? Could you point me to some resources if I am heading in the wrong direction?

**Comment by kratsg** [comment]
There are published likelihoods available for usage here: https://scikit-hep.org/pyhf/citations.html#published-likelihoods - e.g.

```
curl -s -- https://www.hepdata.net/record/resource/1165724?view=true |tar -O -xzvf - - --include patch.ERJR_350p0_0p0.json > patch.ERJR_350p0_0p0.json
curl -s -- https://www.hepdata.net/record/resource/1165724?view=true |tar -O -xzvf - - --include BkgOnly.json > BkgOnly.json
jsonpatch BkgOnly.json patch.ERJR_350p0_0p0.json > my_workspace.json
```

to get an example workspace in practice. The `workspace.json` is just a schema. You should understand the difference between a JSON schema specification and a JSON document that follows the schema.

**Comment by kanishk16** [comment]
Thankyou @kratsg for guiding me. I was grossly wrong and completely mixing up about the 'Workspace' you meant and what I was referring to.  

> There are published likelihoods available for usage here: https://scikit-hep.org/pyhf/citations.html#published-likelihoods - e.g.
> 
> ```
> curl -s -- https://www.hepdata.net/record/resource/1165724?view=true |tar -O -xzvf - - --include patch.ERJR_350p0_0p0.json > patch.ERJR_350p0_0p0.json
> curl -s -- https://www.hepdata.net/record/resource/1165724?view=true |tar -O -xzvf - - --include BkgOnly.json > BkgOnly.json
> jsonpatch BkgOnly.json patch.ERJR_350p0_0p0.json > my_workspace.json
> ```
> 
> to get an example workspace in practice. 

I am not sure if there is any example/tutorial (apart from the toy example in docs) of using published likelihoods but if not, I believe we should add a simple binder ntbk describing to use a published likelihood for new users.

>The `workspace.json` is just a schema. You should understand the difference between a JSON schema specification and a JSON document that follows the schema.

I believe it was due to my confusion but now I am clear about it.
