### ISSUE TITLE
Use pypa readme renderer to figure out how to handle images

### ISSUE THREAD

**Issue by kratsg** [scikit-hep/pyhf#830]
# Question

https://github.com/pypa/readme_renderer seems to be what is used to generate the html page for the README. It seems this should have been fixed according to linked issues/PRs below. But we definitely have issues with the image size of the stackoverflow logo at the bottom here: https://test.pypi.org/project/pyhf/0.4.2.dev20/ . It seems the width attribute is still being stripped from the rST.

# Relevant Issues and Pull Requests

- pypa/readme_renderer#44
- pypa/readme_renderer#114

**Comment by matthewfeickert** [comment]
@dstufft @theacodes @di if you have thoughts here, we would be interested in hearing them. If you would prefer, we can also open up an Issue on [`readme_renderer`](https://github.com/pypa/readme_renderer).

**Comment by di** [comment]
There was a regression ([mentioned here](https://github.com/pypa/readme_renderer/pull/113#discussion_r206366539)) that should be fixed by https://github.com/pypa/readme_renderer/pull/164.

**Comment by matthewfeickert** [comment]
> There was a regression ([mentioned here](https://github.com/pypa/readme_renderer/pull/113#discussion_r206366539)) that should be fixed by [pypa/readme_renderer#164](https://github.com/pypa/readme_renderer/pull/164).

Many thanks for the super speedy diagnosis and reply!

**Comment by matthewfeickert** [comment]
Given @di's super awesome responsiveness the fix for this (https://github.com/pypa/readme_renderer/pull/164) has _already_ gone into a new major release `v26.0` in https://github.com/pypa/readme_renderer/pull/165! As explained in [his comment](https://github.com/pypa/readme_renderer/pull/164#issuecomment-618155969)

> old descriptions should get eventually re-rendered, so you shouldn't have to make a new release to see the update (although new releases will definitely get it right away).

So there should be no further action to take on this. :rocket: 

I won't formally close this Issue until we notice that things render properly on TestPyPI (with prep for patch release v0.4.2 we'll be checking there frequently anyway), but this Issue is resolved now. :+1:

**Comment by matthewfeickert** [comment]
Closing this now as [TestPyPI is rendering fine](https://test.pypi.org/project/pyhf/0.4.2.dev29/). :+1:
